# Generated by Django 6.0.5 on 2026-06-12 13:55

import django.db.models.deletion
import tiqt.apps.ia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_problema', models.TextField(help_text='Como o erro aparece / sintomas observados.')),
                ('solucao', models.TextField(help_text='Passo a passo da solução.')),
                ('palavras_chave', models.CharField(blank=True, help_text='Termos separados por vírgula para ajudar a busca (ex: sefaz, certificado, conexão).', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conhecimentos', to='core.departamento')),
            ],
            options={
                'verbose_name': 'Base de conhecimento',
                'verbose_name_plural': 'Base de conhecimento',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ia_consultas/', validators=[tiqt.apps.ia.models.validar_tamanho_imagem])),
                ('descricao', models.TextField(blank=True, help_text='Descrição do funcionário sobre o que aconteceu.')),
                ('resposta_ia', models.TextField(blank=True)),
                ('resolveu', models.BooleanField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta à IA',
                'verbose_name_plural': 'Consultas à IA',
                'ordering': ['-criado_em'],
            },
        ),
    ]
