# Generated by Django 6.0.5 on 2026-06-12 17:11

import tiqt.apps.ia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ia_consultas/', validators=[tiqt.apps.ia.models.validar_tamanho_imagem]),
        ),
    ]
