# Generated by Django 6.0.5 on 2026-06-24 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_user_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('dia_inteiro', models.BooleanField(default=False)),
                ('origem', models.CharField(choices=[('avulso', 'Avulso'), ('ticket', 'Ticket')], default='avulso', max_length=10)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pendente'), (1, 'Concluído'), (2, 'Cancelado')], default=0)),
                ('notificado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='core.cliente')),
                ('comentario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='core.comentario')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.ticket')),
            ],
            options={
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['inicio'], name='agenda_agen_inicio_b3d8bd_idx'), models.Index(fields=['responsavel', 'status'], name='agenda_agen_respons_fd5f72_idx')],
            },
        ),
    ]
