# Generated by Django 5.1.6 on 2025-03-15 19:55

import tiqt.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='comentarios/arquivos/', validators=[tiqt.apps.core.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios/imagens/', validators=[tiqt.apps.core.models.validate_file_size]),
        ),
    ]
