# Generated by Django 5.1.6 on 2025-03-15 22:02

import tiqt.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentario_arquivo_comentario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=tiqt.apps.core.models.upload_to, validators=[tiqt.apps.core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=tiqt.apps.core.models.upload_to, validators=[tiqt.apps.core.models.validate_file_size]),
        ),
    ]
