# Generated by Django 5.1.6 on 2025-03-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_bairro_alter_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
