# Generated by Django 5.1.6 on 2025-03-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comentario_arquivo_alter_comentario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comentarios_arquivos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.comentario')),
            ],
        ),
    ]
