# Generated by Django 6.0.5 on 2026-07-09 15:33

import django.db.models.deletion
from django.db import migrations, models


def criar_colunas_padrao(apps, schema_editor):
    """Semeia as 3 colunas mapeadas ao fluxo de status, preservando o board atual."""
    KanbanColuna = apps.get_model('core', 'KanbanColuna')
    padrao = [
        ('Aberto', '#00897b', 0, 0),
        ('Em Atendimento', '#fb8c00', 1, 1),
        ('Encerrado', '#388e3c', 2, 2),
    ]
    for nome, cor, ordem, status in padrao:
        KanbanColuna.objects.get_or_create(
            status_associado=status,
            defaults={'nome': nome, 'cor': cor, 'ordem': ordem},
        )


def remover_colunas_padrao(apps, schema_editor):
    KanbanColuna = apps.get_model('core', 'KanbanColuna')
    KanbanColuna.objects.filter(status_associado__in=[0, 1, 2]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cor', models.CharField(default='#607d8b', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('status_associado', models.SmallIntegerField(blank=True, choices=[(0, 'Aberto'), (1, 'Em atendimento'), (2, 'Encerrado'), (3, 'Cancelado')], null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='kanban_ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='kanban_coluna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.kanbancoluna'),
        ),
        migrations.RunPython(criar_colunas_padrao, remover_colunas_padrao),
    ]
