# Generated by Django 5.1.6 on 2025-03-16 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentarioarquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.ticket'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ComentarioImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='comentarios_imagens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.comentario')),
            ],
        ),
    ]
