# Generated by Django 5.1.6 on 2025-03-16 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comentario_options_remove_comentario_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoacao'),
        ),
    ]
