# Generated by Django 6.0.5 on 2026-07-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kanbanquadro_kanbancard'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='kanbancard',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_cards', to='core.ticket'),
        ),
    ]
