# Generated by Django 5.1.6 on 2025-03-24 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comentario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='certificado_digital',
            field=models.FileField(blank=True, default=None, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoacao'),
        ),
    ]
