# Generated by Django 6.0.5 on 2026-07-09 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kanbancard_texto_kanbancard_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.cliente'),
        ),
        migrations.CreateModel(
            name='KanbanCardComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.kanbancard')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
