# Generated by Django 5.1.6 on 2025-03-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_certificado_digital_alter_comentario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='clientes_certificados/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.cliente')),
            ],
        ),
    ]
 