# Generated by Django 6.0.5 on 2026-07-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kanbancard_cliente_kanbancardcomentario'),
        ('mural', '0005_nota_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanban_cards', to='mural.nota'),
        ),
    ]
