# Generated by Django 5.1.6 on 2025-03-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plano_cliente_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.plano'),
        ),
    ]
 