# Generated by Django 5.1.6 on 2025-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50)),
                ('fantasia', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('responsavel', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('inativo', models.BooleanField(default=False)),
                ('motivo_inativacao', models.TextField()),
                ('data_inativacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
