# Generated by Django 6.0.5 on 2026-07-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_kanbancard_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=40)),
                ('cor', models.CharField(default='#61bd4f', max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='cards', to='core.etiqueta'),
        ),
    ]
