# Generated by Django 5.1.6 on 2025-02-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='contato',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
            preserve_default=False,
        ),
    ]
