# Generated by Django 6.0.5 on 2026-07-10 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_etiqueta_kanbancard_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.prioridade'),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
