# Generated by Django 6.0.5 on 2026-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_kanbancard_membros_kanbancard_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanquadro',
            name='fundo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
