# Generated by Django 6.0.5 on 2026-07-13 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_kanbanquadro_fundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanquadro',
            name='departamento_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.departamento'),
        ),
        migrations.CreateModel(
            name='CaixaEntradaRecusa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recusas', to='core.kanbanquadro')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recusa da caixa de entrada',
                'verbose_name_plural': 'Recusas da caixa de entrada',
                'ordering': ['-criado_em'],
                'unique_together': {('quadro', 'ticket')},
            },
        ),
    ]
