# Generated by Django 5.1.6 on 2025-02-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cliente_ativo_alter_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='patrimonio',
        ),
    ]
