# Generated by Django 6.0.5 on 2026-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0014_kanbanquadro_departamento_entrada_caixaentradarecusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanquadro',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='quadros_kanban', to='auth.group'),
        ),
    ]
