# Generated by Django 6.0.5 on 2026-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_kanbanquadro_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
