# Generated by Django 5.1.6 on 2025-02-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_ticket_patrimonio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='setor',
        ),
    ]
