# Generated by Django 6.0.5 on 2026-07-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_kanbancard_concluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_grupos', to='core.kanbanquadro')),
            ],
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='core.kanbangrupo'),
        ),
    ]
