# Generated by Django 5.1.6 on 2025-02-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_ticket_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.departamento'),
        ),
    ]
