# Generated by Django 6.0.5 on 2026-07-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_kanbangrupo_kanbancard_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='quadro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='core.kanbanquadro'),
        ),
    ]
