# Generated by Django 5.1.6 on 2025-02-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ticket_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tributacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
