# Generated by Django 5.1.6 on 2025-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_prioridade_alter_cliente_id_alter_comentario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='descricao',
            field=models.CharField(blank=True, choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta'), (3, 'Urgente')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
