# Generated by Django 6.0.5 on 2026-07-16 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_etiqueta_split_por_quadro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=60)),
                ('recorrente_anual', models.BooleanField(default=False, help_text='Repete todo ano na mesma data (Natal, Tiradentes...). Feriado móvel (Carnaval, Páscoa) deixe desmarcado e cadastre ano a ano.')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.AddField(
            model_name='prioridade',
            name='peso',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maior = mais urgente. Ordena a fila do painel de TV.'),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.SmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expediente',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='SlaPolitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_resposta', models.PositiveIntegerField(help_text='Minutos úteis entre a abertura e o início do atendimento.')),
                ('minutos_resolucao', models.PositiveIntegerField(help_text='Minutos úteis entre a abertura e o encerramento.')),
                ('ativo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, help_text='Vazio = vale para qualquer departamento.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('prioridade', models.ForeignKey(blank=True, help_text='Vazio = vale para qualquer prioridade.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prioridade')),
            ],
            options={
                'verbose_name': 'Política de SLA',
                'verbose_name_plural': 'Políticas de SLA',
                'unique_together': {('departamento', 'prioridade')},
            },
        ),
        migrations.CreateModel(
            name='TicketEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Criado'), (1, 'Atendimento iniciado'), (2, 'Encerrado'), (3, 'Cancelado'), (4, 'Reaberto'), (5, 'Responsável alterado')])),
                ('ocorrido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_de', models.SmallIntegerField(blank=True, null=True)),
                ('status_para', models.SmallIntegerField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, default='', max_length=20)),
                ('estimado', models.BooleanField(default=False)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ticket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ocorrido_em', 'id'],
                'indexes': [models.Index(fields=['ticket', 'ocorrido_em'], name='tktevt_ticket_ocor_idx'), models.Index(fields=['tipo', 'ocorrido_em'], name='tktevt_tipo_ocor_idx')],
            },
        ),
    ]
