# Generated by Django 5.1.6 on 2025-02-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_ticket_prioridade_remove_ticket_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='departamento',
        ),
    ]
