# Generated by Django 5.1.6 on 2025-02-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_tipo_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='prioridade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.prioridade'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.tipo'),
        ),
    ]
