# Generated by Django 5.1.6 on 2025-02-17 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_ticket_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='secretaria',
        ),
        migrations.AddField(
            model_name='tipo',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='descricao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='observacoes',
            field=models.TextField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Secretaria',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
