# Generated by Django 5.1.6 on 2025-02-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_setor_secretaria_tipo_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
