# Generated by Django 5.1.6 on 2025-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cidade_tributacao_uf_remove_cliente_inativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='codigo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='uf',
            name='sigla',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
