# Generated by Django 5.1.6 on 2025-02-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cidade_codigo_uf_sigla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nome',
            new_name='descricao',
        ),
    ]
