# Generated by Django 5.1.6 on 2025-02-19 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_nome_departamento_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='solucao',
        ),
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
