# Generated by Django 5.1.6 on 2025-02-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_ticket_solucao_solucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tributacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tributacao'),
        ),
    ]
