# Generated by Django 6.0.5 on 2026-07-02 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_backfill_proximo_contato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cor', models.CharField(default='#00796b', max_length=7)),
                ('icone', models.CharField(blank=True, max_length=40, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de nota',
                'verbose_name_plural': 'Categorias de notas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'A fazer'), (1, 'Em andamento'), (2, 'Concluída'), (3, 'Arquivada')], default=0)),
                ('prioridade', models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Urgente')], default=0)),
                ('fixado', models.BooleanField(default=False)),
                ('vencimento', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nota', to='agenda.agendamento')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_criadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='mural.categorianota')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fixado', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='mural_arquivos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='mural.nota')),
            ],
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['status'], name='mural_nota_status_6a5ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['categoria'], name='mural_nota_categor_90295a_idx'),
        ),
    ]
