# Generated by Django 6.0.5 on 2026-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0002_seed_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='pos_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='pos_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='z',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
