# Generated by Django 6.0.5 on 2026-07-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_foto'),
        ('mural', '0004_posicoes_por_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_mural', to='core.ticket'),
        ),
    ]
